---
- debug: 
    var: uninstall
    verbosity: 2

- import_tasks: install.yml
  when: (uninstall is undefined or uninstall == False  )

- import_tasks: uninstall.yml
  when: (uninstall is defined and uninstall)
